// <auto-generated />
using System;
using DigiChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigiChat.Infrastructure.Migrations
{
    [DbContext(typeof(DigiChatDbContext))]
    [Migration("20260816050552_AddGenerationDiedUtc")]
    partial class AddGenerationDiedUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigiChat.Domain.Entities.AppState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CurrentGenerationId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStreamSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentGenerationId");

                    b.HasIndex("CurrentStreamSessionId");

                    b.ToTable("AppStates");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.DigimonForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("LineageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineageId", "Stage")
                        .IsUnique();

                    b.ToTable("DigimonForms");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.Generation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UndoneUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Generations");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.Lineage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetReadiness")
                        .HasColumnType("int");

                    b.Property<string>("Canonicality")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceMedia")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Lineages");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.ProcessedChatEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ReceivedUtc");

                    b.ToTable("ProcessedChatEvents");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.StreamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("StreamSessions");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.StreamSessionParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StreamSessionId")
                        .HasColumnType("int");

                    b.Property<int>("ViewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId");

                    b.HasIndex("StreamSessionId", "ViewerId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.TransitionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromGenerationId")
                        .HasColumnType("int");

                    b.Property<int>("FromStage")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ToGenerationId")
                        .HasColumnType("int");

                    b.Property<int>("ToStage")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UndoneUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("Transitions");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.Viewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("Viewers");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.ViewerGenerationAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenerationId")
                        .HasColumnType("int");

                    b.Property<int?>("LineageId")
                        .HasColumnType("int");

                    b.Property<int>("ViewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineageId");

                    b.HasIndex("ViewerId");

                    b.HasIndex("GenerationId", "LineageId")
                        .IsUnique()
                        .HasFilter("[LineageId] IS NOT NULL");

                    b.HasIndex("GenerationId", "ViewerId")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.AppState", b =>
                {
                    b.HasOne("DigiChat.Domain.Entities.Generation", "CurrentGeneration")
                        .WithMany()
                        .HasForeignKey("CurrentGenerationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DigiChat.Domain.Entities.StreamSession", "CurrentStreamSession")
                        .WithMany()
                        .HasForeignKey("CurrentStreamSessionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentGeneration");

                    b.Navigation("CurrentStreamSession");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.DigimonForm", b =>
                {
                    b.HasOne("DigiChat.Domain.Entities.Lineage", "Lineage")
                        .WithMany("Forms")
                        .HasForeignKey("LineageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lineage");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.StreamSessionParticipant", b =>
                {
                    b.HasOne("DigiChat.Domain.Entities.StreamSession", "StreamSession")
                        .WithMany("Participants")
                        .HasForeignKey("StreamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiChat.Domain.Entities.Viewer", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StreamSession");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.ViewerGenerationAssignment", b =>
                {
                    b.HasOne("DigiChat.Domain.Entities.Generation", "Generation")
                        .WithMany("Assignments")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DigiChat.Domain.Entities.Lineage", "Lineage")
                        .WithMany()
                        .HasForeignKey("LineageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DigiChat.Domain.Entities.Viewer", "Viewer")
                        .WithMany("Assignments")
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");

                    b.Navigation("Lineage");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.Generation", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.Lineage", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.StreamSession", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("DigiChat.Domain.Entities.Viewer", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
